package cn.peter.ssm.mapper;

import cn.peter.ssm.pojo.Leaverequest;

import java.util.List;

public interface LeaverequestMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table LEAVEREQUEST
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer l_id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table LEAVEREQUEST
	 *
	 * @mbg.generated
	 */
	int insert(Leaverequest record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table LEAVEREQUEST
	 *
	 * @mbg.generated
	 */
	int insertSelective(Leaverequest record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table LEAVEREQUEST
	 *
	 * @mbg.generated
	 */
	Leaverequest selectByPrimaryKey(Integer l_id);

	/**
	 * added by myself
	 *
	 * @param record
	 * @return
	 */
	List<Leaverequest> selectByAttributeSelective(Leaverequest record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table LEAVEREQUEST
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Leaverequest record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table LEAVEREQUEST
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(Leaverequest record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table LEAVEREQUEST
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Leaverequest record);
}