package cn.peter.ssm.mapper;

import cn.peter.ssm.pojo.Mail;
import cn.peter.ssm.pojo.User;

import java.util.List;

public interface MailMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table MAIL
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer m_id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table MAIL
	 *
	 * @mbg.generated
	 */
	int insert(Mail record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table MAIL
	 *
	 * @mbg.generated
	 */
	int insertSelective(Mail record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table MAIL
	 *
	 * @mbg.generated
	 */
	Mail selectByPrimaryKey(Integer m_id);

	/**
	 * added by myself
	 *
	 * @return List<Mail>
	 */
	List<Mail> listAll();

	/**
	 * added by myself
	 *
	 * @return List<Mail>
	 */
	List<Mail> selectByUser(User user);

	/**
	 * added by myself
	 *
	 * @return List<Mail>
	 */
	List<Mail> selectByTemplate(Mail record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table MAIL
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Mail record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table MAIL
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(Mail record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table MAIL
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Mail record);
}